apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-secret
  namespace: ai-platform
spec:
  containers:
    - name: nginx
      image: nginx:1.27.0
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: API_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: DB_PASSWORD